### ISSUE TITLE
Installer for Mac OSX

### ISSUE THREAD

**Issue by aramzl** [inspectIT/inspectIT#107]
Hi inspectITers,

I would like to installed on  OSX, which is the only OS that we currently have.
The installer on the http://www.inspectit.rocks/ does not work "The inspectIT installer in selected version is not available for the MacOSX. Please select the latest version or visit the GitHub download page for single component packages." In Docker Hub I tried to install the client and it says "This container can only be started on linux with X server, boot2docker will not work." Does it work with docker-machine, there is a new installation of docker on mac, but I think docker-machine is still very popular.

There are a lot of options to install it but it would be nice to have a default one that works out of the box.

Thanks and greetings,

Aram 

PS Does it only works with Java 6 (from 2006), really?

**Comment by ivansenic** [comment]
Hi Aram,

First of all you probably tried to download the Mac installers for the version 1.5.59. For this version they don't exists. But they are available for the latest version that we have: https://github.com/inspectIT/inspectIT/releases/tag/1.6.8.82. The only problem is that the Mac UI in this version has one really big bug at the moment that is solved with the https://github.com/inspectIT/inspectIT/pull/106, but this is not yet integrated. So if you really want to run on Mac you will need to wait for the next version that will include the fix or build your own installer via gradle (based on the fixed PR).

About the docker I need to check further and see what's exactly the problem you are getting. Will come back to you on this topic.

**Comment by ivansenic** [comment]
_PS Does it only works with Java 6 (from 2006), really?_
No works with Java 5+, where did you read that?

**Comment by stefansiegl** [comment]
hey @ivansenic. Anything new for @aramzl regarding this: "Will come back to you on this topic."

**Comment by ivansenic** [comment]
So follow-up for @aramzl:

* About docker not all images are updated yet to the latest version. We will try to have them ready as soon as possible.
* About you comment for Java 6, seams this is a message that you got trying to start the UI in the Mac. Seams this is Eclipse problem in Mac and since we are running on Eclipse platform we get the same. The simple solution is to install this old Java run-time for Mac or start the UI by running directly: ```./inspectit/inspectIT.app/Contents/MacOS/inspectIT```

Hope this helps.

**Comment by stefansiegl** [comment]
So with regards to Docker, we now automated this part as well. For every release that we create the docker images are automatically updated and afterwards built by dockerhub. 

@aramzl could you try out the solution proposed by @ivansenic ?

**Comment by stefansiegl** [comment]
Hi @aramzl, I hope it is fine that I close this issue. Our tests show that the fix of @ivansenic corrected the issue. If you still run in an issue, please re-open the issue or create a new one.

Thank you once again for raising this problem to us.
