### ISSUE TITLE
HTTP Status code not getting displayed in the HTTPTimer Data

### ISSUE THREAD

**Issue by dinesh4747** [inspectIT/inspectIT#212]
Hi InspectIT Team - 

we were currently working on experimenting our commerce application in lower environment using InspectIT 

In Timer data as well as HTTP Timer data i dont see HTTP Status code like HTTP-500/503/502/404 were getting displayed/mentioned 

As per the new feature reported in Confluence (https://inspectit-performance.atlassian.net/browse/INSPECTIT-2230) we should be seeing the status code in HTTP/Invocation data which I am not seeing it 

Even the Invocation Sequences I see that "Status" column is not working and displayed as "Response status unavailable"

Also "Display chat" is not working and doesnt seems to showing the graphical statistics of HTTP count and response time (ms)

**Comment by pbouillet** [comment]
Hi @dinesh4747 

could you tell us a little bit about the technologies / frameworks / servers / jvm version you are using? Especially everything that could be related to http frameworks.

Furthermore, could you provide a screenshot of the invocation sequence and the http view?

Sounds like we are missing some default instrumentations.

**Comment by ivansenic** [comment]
It can be that the Servlet API you are using is lower than version 3.0. If this is the case, inspectIT will not be able to read the response code. It's a limitation that we have currently and it would be nice if we could fix this actually.

**Comment by dinesh4747** [comment]
@pbouillet  - we were working on integrating inspectIT with our apps running in different cloud platforms 

But when i was exploring InspectIT with your sample DVD Store application (/dvdstore/) i am not seeing either HTTP status code as well display chart

I am currently running on my Local Mac Machien

**Comment by dinesh4747** [comment]
@ivansenic - we were currently using Server V 3.1 and i dont think so that would be an issue 

One more thing came up to my mind was Does InspectIT support HTTP2 traffic as well?

**Comment by dinesh4747** [comment]
@pbouillet - Even "Display Chat" doesn't seems to be showing any graphical statistics for the Sample DVD Store Application

**Comment by ivansenic** [comment]
> But when i was exploring InspectIT with your sample DVD Store application (/dvdstore/) i am not seeing either HTTP status code as well display chart

That's because our demo application is very old and uses the Servlet API in the version 2, so the response code are not captured. It should not be a problem with your application I believe. 

> One more thing came up to my mind was does InspectIT support HTTP2 traffic as well?

I see no reason why the HTTP2 would not be supported, that's basically the protocol change, but your application flow remains the same, thus you are still going through filters and servlets that we instrument.

>  Even "Display Chat" doesn't seems to be showing any graphical statistics for the Sample DVD Store Application

Should work out-of-the box. Please not that **Display in chart** by default shows last 15 minutes, so you might need to update the time-frame in the view options (see https://inspectit-performance.atlassian.net/wiki/display/DOC17/Viewing+historical+data).

**Comment by pbouillet** [comment]
Hi @dinesh4747 ,

any news on this issue? Did it work out in the end as @ivansenic suggested?

**Comment by dinesh4747** [comment]
Closing it based on the comments
