### ISSUE TITLE
When Dynamic Instrumentation would be available in InspectIT

### ISSUE THREAD

**Issue by dinesh4747** [inspectIT/inspectIT#213]
Hi Team - 

I could see that there were a ticket on dynamic instrumentation (https://inspectit-performance.atlassian.net/browse/INSPECTIT-1951)

When can we expect this feature getting released? (As per the roadmap it is in V1.9)

Moreover interesting thing is what all the insight/measurement we will get out of this dyn inst feature

If I assumption were right we would be getting following things

1) Method Invocation count

2) CPU %  for each individual method 

3) Call Sequence/flow between incoming/outgoing references for each single method interpretation 

Please do correct If I have misinterpreted anything here

Moreover If we were using dynamic Inst then what would be the JVM Overhead (How much my Application CPU Thread execution time/JVM Heap Usage will impact when we do dyn inst)

In general CPU Samplings/Invocation sequences would be just cause some some non-intrusive overhead may be (~5-10% to JVM CPU) 

Kindly share your thoughts on the same

**Comment by ivansenic** [comment]
Hi @dinesh4747 ,

The dynamic instrumentation will be available in the next preview release version (most likely released on 30.12.2016). 

However, I think you misinterpreted the feature here. Dynamic instrumentation will allow to adapt the instrumentation configuration on the fly without the need to restart the JVM. Currently when you insert instrumentation points with the Instrumentation Manager, you need to restart the application in order for wanted methods to be instrumented. With dynamic instrumentation this will be possible without the restart.

**Comment by pbouillet** [comment]
Hi @dinesh4747 ,

any further questions on this topic? Otherwise I would close it if there is nothing open from your side.

**Comment by dinesh4747** [comment]
No Closing it based on the above comments
