### ISSUE TITLE
 In the test phase, the following problems encountered

### ISSUE THREAD

**Issue by Yangsheng93** [inspectIT/inspectIT#214]
In the test phase, the following problems encountered
      1. When I turn off xshell, CMR will turn off,./start & go backstage too.
      2. UI operation latency is large, whether late consider supporting web UI

**Comment by ivansenic** [comment]
Hi @Yangsheng93,

Can you come over to our chat (https://gitter.im/inspectIT/chat) and we can discuss the problems you encountered?

**Comment by pbouillet** [comment]
Hi @Yangsheng93 , @ivansenic ,

could you solve the problems?

**Comment by pbouillet** [comment]
Closing this ticket for now. Do not hesitate to reopen or create a new one if you have more questions. Thanks!
