### ISSUE TITLE
Does Inspect IT support any of the No-Sql databases 

### ISSUE THREAD

**Issue by dinesh4747** [inspectIT/inspectIT#215]
Does the tool support No-Sql Classification - 

1) "Columnar type database"  - Cassandra/Hbase
2) "Document type database"  - Apache Solr/MongoDB
3) "Key-Value type database" - Redis/Memcache

I Think couple of No-Sql like Cassandra/Hbase/Solr/MondoDB were typically be running any one of the JDK Platforms likely OpenJDK or Oracle Hotspot JVM

**Comment by dinesh4747** [comment]
I totally agree to the point that Redis/Memcache were on C platform and hence it will not supported

**Comment by ivansenic** [comment]
Yes it is true that we don't have let's say direct support for the NoSql database. But this does not mean that you can not monitor them with inspectIT. 

Let's take the Casandra java driver from DataStax as the example. If you use this driver you could easily instrument the [Session](http://docs.datastax.com/en/drivers/java/3.1/com/datastax/driver/core/Session.html) class and monitor it's ```execute``` methods. You could in addition capture the ```query``` parameter and you would be able to see also what query it was. Sure if won't be nicely displayed and organized as for the SQL statements, but at least you could get some basic information.

**Comment by dinesh4747** [comment]
@ivansenic - Thanks for your quick response 

Exactly what we were looking for - In the sense we were using DataStax Cassandra for our core database storage and operations 

So we will try integrating InspectIT and see how it really comes 

Once again appreciate your support and association

**Comment by dinesh4747** [comment]
May be I am asking too many questions all on the trot

Questions were meant to be get the clear understanding of the product and so that we can efficiently use and contribute to the community as well

**Comment by dinesh4747** [comment]
Few more things i was looking for as below:

Does it support the following:

a) Jetty server

b) Node.js 

c) Apache Solr 

I dont see any plugins/agent jar available for any of the above stack - Does anything the team working on/pipeline for the same

**Comment by ivansenic** [comment]
Hi @dinesh4747,

You are welcome to ask as many question as you like. Maybe the best place for such questions is actually our [Gitter chat channel](https://gitter.im/inspectIT/chat). Feel free to drop by..

About the other questions:
* Jetty is supported out of the box, nothing special there
* Node.js is not supported at the moment and there is nobody working on this
* As Apache Solr is running on the plan JVM this is also supported out of the box. 

Don't be confused here, many other similar products in the market have dedicated plug-ins for specific server types or frameworks. As inspectIT is using byte code instrumentation anything that runs in the JVM can be monitored. The thing is only in adapting the instrumentation configuration for specific use-case.

**Comment by pbouillet** [comment]
Hi @dinesh4747 ,

could @ivansenic answer all of your open questions or do you have more regarding no-sql databases etc.?

**Comment by pbouillet** [comment]
Closing this ticket for now. Do not hesitate to reopen or create a new one if you have more questions. Thanks!
