### ISSUE TITLE
How to use the alarm ?

### ISSUE THREAD

**Issue by Yangsheng93** [inspectIT/inspectIT#216]
Hi
   How to use the alarm ? Where to open the alarm ?

**Comment by mariusoe** [comment]
Hi @Yangsheng93,

a detailed description how to setup alerts and thresholds using inspectIT is provided in the [inspectIT documentation](https://inspectit-performance.atlassian.net/wiki/spaces/DOC17).

A description of the alert configuration on the CMR can be found here ([Alerting configuration](https://inspectit-performance.atlassian.net/wiki/display/DOC17/Alerting+configuration)). The process of creating and using thresholds and alerts is provided on the following page ([Setup Alerts and Thresholds](https://inspectit-performance.atlassian.net/wiki/display/DOC17/Setup+Alerts+and+Thresholds)).

I hope this will help you.

**Comment by pbouillet** [comment]
Hi @Yangsheng93 ,

could you already take a look at the provided documentation and did it help you? It is always important for us that the documentation helps the users and you basically find all the information there. If something is unclear or missing, please let us know!

**Comment by pbouillet** [comment]
Closing this ticket for now. Do not hesitate to reopen or create a new one if you have more questions. Thanks!
