### ISSUE TITLE
InspectIT java agent can not connect to CMR which was deployed on Solaris 5.10(SunOS)

### ISSUE THREAD

**Issue by youjenli** [inspectIT/inspectIT#231]
Hi, maintainers of InspectIT:

We want to introduce a free APM solution to monitor on-premise web systems in our company.
One of our conern is that we have several web systems which was deployed to Weblogic on Solaris.
Since InspectIT 1.7.7.90 is a candidate among all feasible solutions, we expect it to be able to monitor these systems.  

Inorder to verify the compatibility of InspectIT, we have configured our startup script of weblogic to import InspectIT's java agent and let it send metrics to a CMR which was deployed to the same server node as well as Weblogic.  
During this verification process we found out that java agent is able to reach CMR. But for unknown reason, the inspectit client shows that java agent was not connected.

![inspectit1 7 7 90 java agent cmr](https://cloud.githubusercontent.com/assets/1283378/22959110/7ac2f258-f36e-11e6-934c-9c75f4ba91da.png)

It looks like the log file of java agent and cmr does not have sufficient clues to diagnose this problem.
We wonder how to resolve this issue?  
Please feel free to ask for further information.  

Any suggestion will be appreciated, thank you.  

### Environment

**OS**: SunOS TWAP27 5.10 Generic_137138-09 i86pc i386 i86pc  
**Firewall**: disabled.  

**Weblogic 10.3.0.0** running with jvm below:  
````
java version "1.6.0_14"
Java(TM) SE Runtime Environment (build 1.6.0_14-b08)
Java HotSpot(TM) Server VM (build 14.0-b16, mixed mode)
```` 

**InspectIT Java Agent**: [1.7.7.90][Javaagent]  
**InspectIT CMR**: [1.7.7.90 Linux x64][CMR]
The jre bundled with CMR has been substituded by JVM:  
````
java version "1.7.0_67"
Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
Java HotSpot(TM) Server VM (build 24.65-b04, mixed mode)
````

[CMR]: https://github.com/inspectIT/inspectIT/releases/download/1.7.7.90/inspectit-cmr.linux.x64-1.7.7.90.zip "InspectIT CMR 1.7.7.90"
[Javaagent]: https://github.com/inspectIT/inspectIT/releases/download/1.7.7.90/inspectit-agent-java6-1.7.7.90.zip "InspectIT java agent 1.7.7.90"

### Logs
Time Zone: UTC+8
#### InspectIT java agent
[agent.log][agent log].
The [exception.log][exception log] is empty.

[agent log]: https://drive.google.com/file/d/0BxfRIIL6wqYuRGlQU1VRbkhQN2s/view?usp=sharing "java agent log"
[exception log]: https://drive.google.com/file/d/0BxfRIIL6wqYuVHlsOUx2djQ4UmM/view?usp=sharing "java agent exception log"

#### InspectIT CMR
[cmr logs directory][cmr logs]

[cmr logs]: https://drive.google.com/drive/folders/0BxfRIIL6wqYuSEs0ZGxmR2gwbE0?usp=sharing "inspectit cmr log files"

#### Weblogic
The standard output message of bash shell terminal has been recorded in [dcmout.log][dcmout.log]
The standard error message of of bash shell terminal has been recorded in [dcmerr.log][dcmerr.log]

[dcmout.log]: https://drive.google.com/file/d/0BxfRIIL6wqYuLTlPQ1kzMlp4bVU/view?usp=sharing "weblogic standard output message"
[dcmerr.log]: https://drive.google.com/file/d/0BxfRIIL6wqYuNmhsdXBmVUxJVjQ/view?usp=sharing "weblogic standard error message"

#### Scripts
We use [runs1a.sh][runs1a.sh] to start weblogic, [kill.sh][kill.sh] to stop all java application, [dcmsit-solaris-inspectit-startup.sh][startup automation] to automate the startup process of CMR and weblogic.

[runs1a.sh]: https://drive.google.com/file/d/0BxfRIIL6wqYuYUFlTHgxb2hNN0E/view?usp=sharing "start weblogic" 
[kill.sh]: https://drive.google.com/file/d/0BxfRIIL6wqYucjYxUW0xT25pS28/view?usp=sharing "stop all java application"
[startup automation]: https://drive.google.com/file/d/0BxfRIIL6wqYuRkxVQ2VCdTlyeDA/view?usp=sharing "CMR and weblogic startup automation"

**Comment by pbouillet** [comment]
Hi @youjenli ,

thanks for reaching out to us!

It's interesting to me that the agent stops at some point with the logging but in the UI you can clearly see that at least once the connection has succeeded. Could you send me in addition the log on the CMR? Maybe this will give additional hints on what has happened.

**Comment by youjenli** [comment]
[cmr log files][cmr log files]

By the way, everything looks fine when we try to monitor a [spring-petclinic-rest][spring-petclinic-rest] app deployed to tomcat 8.0.41 instead of weblogic on the same SunOS.

![inspectit tomcat8 0 41 spring-pet-clinic](https://cloud.githubusercontent.com/assets/1283378/22966651/15fbcc34-f39e-11e6-8d46-a50af3a32628.png)

[spring-petclinic-rest]: https://github.com/spring-petclinic/spring-petclinic-rest "spring petclinic rest version"
[cmr log files]: https://drive.google.com/drive/folders/0BxfRIIL6wqYuSEs0ZGxmR2gwbE0?usp=sharing "inspectit cmr log files"

**Comment by ivansenic** [comment]
Hi all,

This seams very much like the problem described in the [INSPECTIT-2206](https://inspectit-performance.atlassian.net/browse/INSPECTIT-2206). The only way to overcome this is the [workaround](https://inspectit-performance.atlassian.net/browse/INSPECTIT-2206?focusedCommentId=24201&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-24201) I described in one of the comments. The question remains if the workaround affects correct functioning of the WebLogic then or not. 

@youjenli Maybe you can try this out and let us know if this works for you? If not then we need to figure something out.

**Comment by youjenli** [comment]
It looks like `javax.xml.parsers.SAXParserFactory` was not packed into our `weblogic.jar`..... That blows. 

In addition to information I have provided, my colleague just told me that this issue rises in the case of latest release `1.6.9.83`, too.  
He found out that he could let CMR (1.6.9.83) behaves properly if he remove the `logging-config.xml` from the directory java agent.  
By telling you this case, I hope I could help you diagnose this problem.

**Comment by pbouillet** [comment]
This is really interesting. Logging always is something that bothers us as no matter how much you try to seperate it from the target application, there is always a small overlapping in between. Do I understand you correctly that at least you get it now to work if you remove this logging file? At least you would have a temporary solution to your problem.

**Comment by youjenli** [comment]
Hi @ivansenic

The approach you provided works! Thank you!  
But for operation management purpose, I wonder if there is any else way that does not include custom modification to software executables of Weblogic?  

Could I overcome this problem by having some special software configuration to Weblogic or InspectIT?

**Comment by ivansenic** [comment]
Hi @youjenli,

Problem is that Weblogic has setting for a specific SAX parser factory and when we try to initialize logging in inspectIT it fails as class ```weblogic.xml.jaxp.RegistrySAXParserFactory``` can not be found. The solution could be to find out which Weblogic jar contains this class and then adding this jar to the boot class path with additional JVM start parameter:

```-Xbootclasspath/p:[PATH_TO_JAR]```

Maybe you can try that out and let us know if this worked?

**Comment by youjenli** [comment]
Thanks for your help!

That class `weblogic.xml.jaxp.RegistrySAXParserFactory` in Weblogic **10.3** was placed in `weblogic/xml/jaxp` folder inside `weblogic.jar`, which you have mentioned in the workaround of INSPECTIT-2206.  
My instinct told me that my issue may be related to a [bug][weblogic bug] reported at Weblogic community.  

As you see, the method `setXinludeAware` in `weblogic.xml.jaxp.RegistrySAXParserFactory` is misspelling, just like what they said in discussion thread.  

![weblogic-jar saxparserfactory](https://cloud.githubusercontent.com/assets/1283378/24182161/d1966004-0efa-11e7-9606-1695a9876ea5.png)

I have tried to make InspectIT agent work properly (i.e. able to log and connect to CMR) by following the approach mentioned in that thread, which means replacing the SAXParserFactory implementation of Weblogic with `com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl` through `JAVA_OPTIONS` environment variable of Weblogic startup script.  
Unfortunately, this approach doesn't work.

Since we doesn't know much about the inspectit agent, I hope by providing this information to you could help your team figure out an approach to make InspectIT agent work propertly on Weblogic 10.3 without custom modification to software package.

[weblogic bug]:https://community.oracle.com/thread/913954 "Weblogic bug"

**Comment by ivansenic** [comment]
Hi @youjenli,

We originally tried to solve this by adding this line to our _LogInitializer_ class: https://github.com/inspectIT/inspectIT/blob/master/inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/logback/LogInitializer.java#L59. We did this in order to ignore possibility of specifying some other parser factory. That's why your hack is not working.

Can you try to start the weblogic without inspectIT and with the Sun implementation of the parser factory? Would this work in terms of if the server would be correctly started and running? If this would be the case, then I can easily remove this additional lines we added and user could decide which factory to use on it's own.

**Comment by youjenli** [comment]
@ivansenic
It seems that Weblogic is able startup seccessfully if I have replaced the SAXParserFactory implementation with `com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl` on both [`10.3.0`][10.3.0 log file] and [`10.3.6`][10.3.6 log file].

[10.3.0 log file]: https://drive.google.com/drive/folders/0BxfRIIL6wqYuZ2xXd3hDenVYMzg?usp=sharing "Weblogic 10.3.0 startup log"
[10.3.6 log file]: https://drive.google.com/drive/folders/0BxfRIIL6wqYuc1NEdzVkbHZUZ2M?usp=sharing "Weblogic 10.3.6 startup log"

**Comment by ivansenic** [comment]
@youjenli 

Great. We reopened the https://inspectit-performance.atlassian.net/browse/INSPECTIT-2206 and will then change the code a bit so that the ```com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl``` is used when we initialize the logging. Should be solved fast.

Regarding building of the agent,  running the ```./gradlew release``` command in the inspectIT root repository directory will release all the artifacts.. You can find them then in the ```build/release/``` and ```build/release/packages/```.

One last thing, I sent you a private email yesterday, did you got it? I sent it to your e-mail address displayed on your GitHub profile.

**Comment by ivansenic** [comment]
Soved by #254

**Comment by ivansenic** [comment]
@youjenli The fix has been merged and included in the newest release. Can you check if it works for you please so that I can close the issue.

**Comment by youjenli** [comment]
@ivansenic

It seems that we won't have to modify jar file of Weblogic or removing logging configuration from agent to make agent work properly now.
Thanks for you work!
