### ISSUE TITLE
No refresh of agent status on agent reconnect

### ISSUE THREAD

**Issue by maccloud42** [inspectIT/inspectIT#247]
RHEL 7, InspectIT 1.7.8.91. When restarting agent processes the agent status in the GUI is not updated from "Not connected" to "Sending data". A restart of the GUI does not solve the problem. The CMR log confirms that the agents have reconnected and data is indeed received and displayed by the GUI.

**Comment by maccloud42** [comment]
I think this is covered in  INSPECTIT-2322, sorry.

**Comment by ivansenic** [comment]
Already covered by #227

**Comment by ivansenic** [comment]
Fixed by #326
