### ISSUE TITLE
Kubernetes Support

### ISSUE THREAD

**Issue by rikatz** [inspectIT/inspectIT#253]
I don't know if this is the case, but I'm looking for some good APM for my environment (preference to Opensource one).

I've found some very good commercial solutions, like CoScale and Datadog, that can monitor and correlate objects inside a Kubernetes Cluster.

It would be great if InspecIT also support this kind of integration, so we can have a full visualization of an application running inside Kubernetes, with the quantity of Pods running in a ReplicaSet, correlation between services and so.

This is just a Feature Request :)

Thanks!

**Comment by pbouillet** [comment]
Thanks for that feature request, this definitely sounds interesting! Do you know how CoScale and Datadog represent this information?

**Comment by rikatz** [comment]
@pbouillet sorry for taking so long to answer, I was travelling :)

Basically I've seen that CoScale  gathers those informations from Kubernetes API and assembles them like this: http://container-solutions.com/content/uploads/2016/09/app.coscale.com-app-00dc3396-54b9-4a9e-9752-13f6c73a872a-dashboard-view-8860-1.png

But this is a general overview, having a view per Namespace and Apps / ReplicaSet is something like this: http://www.coscale.com/hubfs/Blog_Pictures/2016_05/Kubernetes_monitoring.png

You have a nice feature description here: http://www.coscale.com/blog/how-to-monitor-your-kubernetes-cluster

But basically, the component in Kubernetes that gather those informations is Heapster (the CPU/Memory/Disk/Network usage per POD), and you also have the infos about quantity of PODs per RS, PODs running, PODs with problems and also the events directly in Kubernetes API.

I think we can start (I can help with some stuffs, but I'm not a pretty good Go developer ;P ) mapping these RS / PODs status, and then we can try later to gather the infos from Heapster also to correlate them all.

What do you think about that? 

Thanks!!
