### ISSUE TITLE
New instance of JVM information dash board display legacy data.

### ISSUE THREAD

**Issue by youjenli** [inspectIT/inspectIT#259]
Hi everyone

I want to build up a new and complete monitoring stack (Influxdb 1.0.0 + CMR 1.7.9.92 + Grafana 4.2) on Linux today.
I have followed the sequence in brackets in previous sentence to install and startup these software, except that I have connect to CMR with another client which has already connected to two existing CMR after the new CMR (cmr-1.7.9.92-Influxdb@192.168.209.118) was installed.

![agent -2017-4-17-1745-25](https://cloud.githubusercontent.com/assets/1283378/25086544/fd5959da-239a-11e7-8237-3b6dd5467c29.png)

I was surprised that the jvm information view of Grafana is able to display information about legacy agent, even agent if 1.7.8.91 is avalilable, too.

![jvm-information-2017-4-17-1731-08](https://cloud.githubusercontent.com/assets/1283378/25086502/ae28d6ba-239a-11e7-995a-b5fa77844827.png)

Is this a bug?
How to reset these data to build up a clean monitoring stack?

Please feel free to ask more information.

**Comment by youjenli** [comment]
Today I realized that repository configuration widget of CMR may recongnized input string of `Host` field as a host name related to InspectIT client, not CMR, therefore CMR will not connect to Influxdb which I have deployed with CMR in the same host if I assign Host to **localhost** at the client.
Perhaps that's why Grafana gets legacy data from Influxdb which I have setup in the same PC with InspectIT client.

**Comment by ivansenic** [comment]
Hi @youjenli,

The information in the influxDB is long term monitoring data and thus we don't delete this information on our own. You need to delete this information if you want manually. You can use the official influxDB for more info: https://docs.influxdata.com/influxdb/v1.2/query_language/database_management/#delete-series-with-delete

Alternatively you can drop the whole influxDB database and tell CMR to write to a new one (just rename database name in the influxdb properties). This way you get clean start.
