### ISSUE TITLE
System Information tables in JVM Information dashboard merely display information of particular system.

### ISSUE THREAD

**Issue by youjenli** [inspectIT/inspectIT#270]
Today I found out that no matter which agent I have selected in JVM Information dashboard, the content of `General System Information` as well as `System Memory Information` never change.

I think this is because there's no **where clouse** in the query of metrics.

![missing-where-clause-2017-5-2- -11-33-20](https://cloud.githubusercontent.com/assets/1283378/25603362/a75f96ae-2f2d-11e7-89bd-21cf08d1831a.png)

Thus I add `where "agentName" =~ /^$AgentName$/` to all query of these tables. And It looks fine now.

![general-system-information- -2017-5-2- -10-19-14](https://cloud.githubusercontent.com/assets/1283378/25603369/b15874f0-2f2d-11e7-891f-ab0ea8c7bf35.png)

Since I am not pretty familiar with Grafana, I'd like to know whether this is an appropriate approach to fix this problem?

**Comment by ivansenic** [comment]
Also confirmed bug, we will tackle this one in https://inspectit-performance.atlassian.net/browse/INSPECTIT-2399 as well.

@youjenli Thanks

**Comment by mariusoe** [comment]
Has been fixed in the ticket specified by @ivansenic.
