### ISSUE TITLE
Jackson exception when calling rest/data/invocations/

### ISSUE THREAD

**Issue by chrisehlen** [inspectIT/inspectIT#305]
When calling rest/data/invocations/ Rest endpoint we are getting the error below.  I think the issue was introduced in the "INSPECTIT-2276: UI views for tracing" commit. A new method getRoot() was added to the rocks.inspectit.shared.all.tracing.data.SpanIdent class and it is conflicting with isRoot().

`{"error":"Could not write JSON: Conflicting getter definitions for property \"root\": rocks.inspectit.shared.all.tracing.data.SpanIdent#getRoot(0 params) vs rocks.inspectit.shared.all.tracing.data.SpanIdent#isRoot(0 params) (through reference chain: java.util.ArrayList[0]->rocks.inspectit.shared.all.communication.data.InvocationSequenceData[\"spanIdent\"]); nested exception is org.codehaus.jackson.map.JsonMappingException: Conflicting getter definitions for property \"root\": rocks.inspectit.shared.all.tracing.data.SpanIdent#getRoot(0 params) vs rocks.inspectit.shared.all.tracing.data.SpanIdent#isRoot(0 params) (through reference chain: java.util.ArrayList[0]->rocks.inspectit.shared.all.communication.data.InvocationSequenceData[\"spanIdent\"])","exceptionType":"org.springframework.http.converter.HttpMessageNotWritableException"}`

**Comment by pbouillet** [comment]
Thanks for the report! I have created a Jira ticket out of this (https://inspectit-performance.atlassian.net/browse/INSPECTIT-2469).
