### ISSUE TITLE
Infinite loop when opening the invocation sequence of a method

### ISSUE THREAD

**Issue by theobisproject** [inspectIT/inspectIT#327]
In the newest 1.8.2 release I'm no longer able to open the invocation sequence of a method. The operation hangs in the state of the attached image. The only way to stop the operation is to kill the application over the task manager.  
![grafik](https://user-images.githubusercontent.com/3966701/28679952-1482e0b4-72f5-11e7-8db8-c64b41326a5f.png)

OS: Windows 10
InspectIT version: 1.8.2.96
The CMR is running in the official docker container

**Comment by mariusoe** [comment]
Hi @theobisproject,

thanks for the bug report.

We are aware of this bug and we already provided a fix for it in the following ticket: https://inspectit-performance.atlassian.net/browse/INSPECTIT-2495

The fix will be part of the next version we release.

Greets,
Marius

**Comment by ivansenic** [comment]
Fixed by #322
