### ISSUE TITLE
Agent Configuration Options, Ignore Spring

### ISSUE THREAD

**Issue by kingargyle** [inspectIT/inspectIT#352]
Is there a way to have the agent ignore setting up a Spring configuration.   We have a weird hybrid application that even though it has Spring in it, it isn't the primary way the classes are launched within the application.  So right now it only seems to be capturing metrics for classes that are launched through spring.  I'd like it to capture metrics for all classes regardless of how they are loaded.  I can then include exclusions to filter out the information I don't care about.

**Comment by pbouillet** [comment]
For inspectIT it is irrelevant on how the classes are loaded. Did you change the configuration to include your own classes which you want to analyze / monitor? If not, take a look at our documentation on how to do so: https://inspectit-performance.atlassian.net/wiki/x/ejWLBQ

Let me know if this works out or not.

**Comment by kingargyle** [comment]
Thanks.  I just discovered that I needed to create the custom profiles for the inspections on which packages.  I'm closing this now.  Helps if I read the documentation more.
