### ISSUE TITLE
InspectIT agent on TIBCO appliation 

### ISSUE THREAD

**Issue by prashantnitt07** [inspectIT/inspectIT#355]
hi ,
please suggest me , can be deploy InspectIT agent on TIBCO application .

InspectIT  APM tool is supported for TIBCO application.

**Comment by ivansenic** [comment]
Hi @prashantnitt07,

I really can not say, because we never tried it on the TIBCO app. But if it's running in the JVM (and I think it does) then it should be possible. Why don't you try it out?

**Comment by prashantnitt07** [comment]
ok got it
