### ISSUE TITLE
InspectIT - CMR start error 

### ISSUE THREAD

**Issue by prashantnitt07** [inspectIT/inspectIT#358]
Team ,
we are getting error when starting CMR start services...
please find below error and help me

```
2017-10-05 18:04:51,533: 12626  [           main] INFO      rocks.inspectit.server.CMR - Starting CMR in version 1.7.11.94. Please note that inspectIT does not provide any guarantee on backwards compatibility. Only if the version match exactly we ensure that the components are compatible.
2017-10-05 18:04:51,533: 12626  [           main] INFO      rocks.inspectit.server.CMR - CMR started in 12380.229558 ms
```

**Comment by ivansenic** [comment]
What kind of error are you referring to. This is normal start-up log output?

**Comment by prashantnitt07** [comment]
we are installing InspectIT on Linux machine 


----------------------------------------------------------------------------------------------------------------
Select Installation Packages
----------------------------------------------------------------------------------------------------------------

1    [x] [inspectIT UI] (130.34 MB)
2    [x] [inspectIT Server (CMR)] (123.57 MB)
3    [x] [inspectIT Java Agent] (9.41 MB)
Total space required: 263.32 MB
Press 0 to confirm your selections.
Please select which packs you want to install.
0
Done!

Press 1 to continue, 2 to quit, 3 to redisplay
1

----------------------------------------------------------------------------------------------------------------
Installation
----------------------------------------------------------------------------------------------------------------

[ Starting to unpack ]
[ Processing package: inspectIT UI (1/3) ]
[ Processing package: inspectIT Server (CMR) (2/3) ]
[ Processing package: inspectIT Java Agent (3/3) ]
[ Unpacking finished ]

----------------------------------------------------------------------------------------------------------------
Setup Shortcuts
----------------------------------------------------------------------------------------------------------------

----------------------------------
Create shortcuts in the Start-Menu
----------------------------------
Enter Y for Yes, N for No:
y
------------------------------------------
Create additional shortcuts on the desktop
------------------------------------------
Enter Y for Yes, N for No:
Y
Could not copy terminal to /home/jiotools/.local/share/pixmaps/terminal (terminal (No such file or directory))
Could not copy trashcan_full to /home/jiotools/.local/share/pixmaps/trashcan_full (trashcan_full (No such file or directory))

----------------------------------------------------------------------------------------------------------------
Installation Finished
----------------------------------------------------------------------------------------------------------------

-----------------------------------------
Generate an automatic installation script
-----------------------------------------
Enter Y for Yes, N for No:
Y
Select the installation script (path must be absolute)[/EM/inspectIT/auto-install.xml]

Installation was successful
Application installed on /EM/inspectIT

----------------------------------------------------------------------------------------------------------------
Installation Finished
----------------------------------------------------------------------------------------------------------------

Installation was successful
Application installed on /EM/inspectIT
[ Writing the uninstaller data ... ]
[ Console installation done ]
------------------------------------------------------------------
# what is next step after that , we use web ----------------------------------------------------------------------------------------------------------------
Select Installation Packages
----------------------------------------------------------------------------------------------------------------

1    [x] [inspectIT UI] (130.34 MB)
2    [x] [inspectIT Server (CMR)] (123.57 MB)
3    [x] [inspectIT Java Agent] (9.41 MB)
Total space required: 263.32 MB
Press 0 to confirm your selections.
Please select which packs you want to install.
0
Done!

Press 1 to continue, 2 to quit, 3 to redisplay
1

----------------------------------------------------------------------------------------------------------------
Installation
----------------------------------------------------------------------------------------------------------------

[ Starting to unpack ]
[ Processing package: inspectIT UI (1/3) ]
[ Processing package: inspectIT Server (CMR) (2/3) ]
[ Processing package: inspectIT Java Agent (3/3) ]
[ Unpacking finished ]

----------------------------------------------------------------------------------------------------------------
Setup Shortcuts
----------------------------------------------------------------------------------------------------------------

----------------------------------
Create shortcuts in the Start-Menu
----------------------------------
Enter Y for Yes, N for No:
y
------------------------------------------
Create additional shortcuts on the desktop
------------------------------------------
Enter Y for Yes, N for No:
Y
Could not copy terminal to /home/jiotools/.local/share/pixmaps/terminal (terminal (No such file or directory))
Could not copy trashcan_full to /home/jiotools/.local/share/pixmaps/trashcan_full (trashcan_full (No such file or directory))

----------------------------------------------------------------------------------------------------------------
Installation Finished
----------------------------------------------------------------------------------------------------------------

-----------------------------------------
Generate an automatic installation script
-----------------------------------------
Enter Y for Yes, N for No:
Y
Select the installation script (path must be absolute)[/EM/inspectIT/auto-install.xml]

Installation was successful
Application installed on /EM/inspectIT

----------------------------------------------------------------------------------------------------------------
Installation Finished
----------------------------------------------------------------------------------------------------------------

Installation was successful
Application installed on /EM/inspectIT
[ Writing the uninstaller data ... ]
[ Console installation done ]   

----------------------------
# what is next step after that , we use web consel to Inspect IT web consel

**Comment by ivansenic** [comment]
After installation.

1. Start CMR (as you did already) by running the `[CMR ROOT]/start.sh` script
2. Install inspectIT UI on your local machines and start it
3. Connect to the CMR you started, by adding new repository in the inspectIT UI and entering the IP address of the machine where CMR runs
4. Add inspectIT agent to start-up parameters of the JVM you want to monitor: `-javaagent:[INSPECTIT_AGENT_HOME]/inspectit-agent.jar -Dinspectit.repository=[IP_OF_MACHINE_WHERE_CMR_RUNS]:9070 -Dinspectit.agent.name=[AGENT_DISPLAY_NAME]`
5. Read [documentation](https://inspectit-performance.atlassian.net/wiki/spaces/DOC18/pages/93009357/inspectIT+Big+Picture+Scope) for further instructions, configuration guidelines and other details

**Comment by prashantnitt07** [comment]
we are getting log error 
log file name : statistics.log 


2017-10-05 19:10:59,926: Status of the Write Channel Manager's executor service: java.util.concurrent.ThreadPoolExecutor@24d19572[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
2017-10-05 19:10:59,926: Status of each writable storage and its executor service:
2017-10-05 19:10:59,926: No active writable storage available.
2017-10-05 19:10:59,926: Recording is not active.
2017-10-05 19:10:59,926: Byte buffer provider has 0 available buffers in the pool with total capacity of 0 bytes. Total created capacity of the pool is 0 bytes. 

--------------------------------------UI error -----------------------
19:15:18.257 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - Scanning bundle [Workbench (org.eclipse.ui.workbench; singleton:=true)] for configurations...
19:15:18.257 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - Creating an application context for bundle [Workbench (org.eclipse.ui.workbench; singleton:=true)]
19:15:18.265 [main] DEBUG org.springframework.osgi.extender.internal.activator.ContextLoaderListener - No application context created for bundle [Workbench (org.eclipse.ui.workbench; singleton:=true)]
InspectIT:
An error has occurred. See the log file
/EM/inspectIT/inspectit/workspace/.metadata/.log.

--please help here ---

**Comment by ivansenic** [comment]
Our UI is desktop based, fat UI client. It's based on Eclipse. You must try to start it on the OS that has graphical user interface. You can not running on your server, if that is what you are trying? It's not a web-based UI (see screenshots on our github page). Idea is that you install UI on your local machine (Windows, Ubuntu, Mac) and then connect to the CMR that runs on one of your servers in order to work with it.

**Comment by prashantnitt07** [comment]
yes I understand ..
but CRM not started and we are getting error, if CMR not started , how can connect ..

EM/inspectIT/CMR
 ./startup.sh

after line 2017-10-05 18:04:51,533: 12626  [           main] INFO      rocks.inspectit.server.CMR - CMR started in 12380.229558 ms  not displaying  any thing 

how can check CMR started or not 
------------------------------------------
2017-10-05 18:04:51,533: 12626  [           main] INFO      rocks.inspectit.server.CMR - Starting CMR in version 1.7.11.94. Please note that inspectIT does not provide any guarantee on backwards compatibility. Only if the version match exactly we ensure that the components are compatible.
2017-10-05 18:04:51,533: 12626  [           main] INFO      rocks.inspectit.server.CMR - CMR started in 12380.229558 ms

**Comment by ivansenic** [comment]
The line `2017-10-05 18:04:51,533: 12626 [ main] INFO rocks.inspectit.server.CMR - CMR started in 12380.229558 ms` means that CMR has successfully started, after total of 12,3 seconds. **So yes it is started without any errors.**

**Comment by ivansenic** [comment]
Closing as there is no real issue here imo.
