### ISSUE TITLE
Issue with Java Agent 

### ISSUE THREAD

**Issue by FrancescoOriglia** [inspectIT/inspectIT#377]
Hello,

We find your tool really interesting but we have actually an issue. We can start CMR successfully, but when we start the java agent he have  " sending data " status for maybe 10 seconds then he become " disconnected ". 

![disconnected](https://user-images.githubusercontent.com/19547118/35517167-f4b508f6-050d-11e8-9202-b3732194d45e.PNG)

If you have an idea, I will be happy to try it.

Sincerely,
Francesco

**Comment by ivansenic** [comment]
Did you add any custom instrumentation points in your configuration? Any chance you used wild-card `*` to instrument too many classes?

**Comment by FrancescoOriglia** [comment]
I didn't do anything yet. I just started CMR and added the agent with the command line : 

java -javaagent:/usr/local/inspectIT/agent/inspectit-agent.jar -Dinspectit.repository=localhost:9070 -Dinspectit.agent.name=test

I'm actually on a virtual machine ( CentOS 7 )

**Comment by ivansenic** [comment]
Any chance you can zip and attach here the `[CMR]/logs` folder. That would be helpful. However, I think I hit something similar today. I just want to check if this is the case. If so we'll try to fix it asap.

**Comment by FrancescoOriglia** [comment]
There is the folder. Thank you for your help.

[logs.zip](https://github.com/inspectIT/inspectIT/files/1677794/logs.zip)

**Comment by ivansenic** [comment]
Nothing interesting there. Can you do the same with `[agent]/logs` folder, please?

**Comment by FrancescoOriglia** [comment]
Sure : 

[logsAgent.zip](https://github.com/inspectIT/inspectIT/files/1677842/logsAgent.zip)

**Comment by ivansenic** [comment]
I see nothing strange in your logs. It's behaving exactly as it should. 

Seams that simply the Java program you are trying to run is lasting really short. When the JVM is terminated, the agent is of course disconnected from the CMR. It's a normal behavior.

Please test/check our demo application: https://github.com/inspectit-labs/spring-petclinic-microservices, this one starts and runs until explicitly stopped, you can test all features of inspectIT. It's a simple webapp.

I am closing this issue for now as I see nothing we can do.

**Comment by FrancescoOriglia** [comment]
My application is a simple java Hello world sample, she is always running, I don't understand why it can't work. Even if I use your demo application, If I can't monitor mine, that will be useless.
If you have an other idea, I will be really thankful.

**Comment by ivansenic** [comment]
Can you share your HelloWorld sample, please? Let's clarify this.

**Comment by FrancescoOriglia** [comment]
Here he is : 

[sample.zip](https://github.com/inspectIT/inspectIT/files/1678205/sample.zip)

Thank you for your consideration.

**Comment by ivansenic** [comment]
Your example does not contain manifest file. Meaning that when I start, I am ending up in:
```
$ java -jar helloworld.war
no main manifest attribute, in helloworld.war
```
However, not having manifest does not mean that the JVM is not started. When you hook `inspectit-agent.jar` the JVM including the inspectit agent is running so long for this message to be printed out. After that JVM is terminated and agent disconnected. 

Or you are using some other command to start your program? Please let me know..

**Comment by FrancescoOriglia** [comment]
The manifest file is created when you start the Tomcat server (It create a folder with the same name as the war file).
I just sent you the war file. I think we misunderstood.

There is the folder : 

[SampleTest.zip](https://github.com/inspectIT/inspectIT/files/1678342/SampleTest.zip)

**Comment by ivansenic** [comment]
OK, so you are starting the Tomcat server to run this app? Can you tell me how do you add the `inspectit-agent.jar` to the start-up parameters of the Tomcat? Have you followed the instructions here: https://inspectit-performance.atlassian.net/wiki/spaces/DOC18/pages/93009253/Installation+Tomcat?

**Comment by FrancescoOriglia** [comment]
Yes I use Tomcat, I have add the following code to catalina.sh script : 

INSPECTIT_AGENT_HOME="/usr/local/inspectIT/agent"
export INSPECTIT_AGENT_HOME
 
INSPECTIT_JAVA_OPTS="-javaagent:${INSPECTIT_AGENT_HOME}/inspectit-agent.jar -Dinspectit.repository=localhost: -Dinspectit.agent.name=testing"
export INSPECTIT_JAVA_OPTS
 
# integrate inspectit java options with the java options of Tomcat
JAVA_OPTS="${INSPECTIT_JAVA_OPTS} ${JAVA_OPTS}"

We must put it somewhere or we are free to choose ?

**Comment by ivansenic** [comment]
This should be fine, if you added this before the java command that runs the Tomcat is called in the `catalina.sh`. I will invest some time soon in order to setup exact same scenario as you (tomcat+simpleApp) and check if there are any problems. Will inform you.

**Comment by FrancescoOriglia** [comment]
Thank you for your help.

**Comment by FrancescoOriglia** [comment]
I have just change the position of the code in catalina.sh and it's now working fine.
Anyway thank you for your help.
I will try it really soon !
