### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by abk267** [inspectIT/inspectIT#386]
I have a java webapp ( tomcat server ) . Trying to use inspectj is giving 

ERROR java.core.impl.PlatformManager - Connection to the server failed.
java.net.ConnectException: Connection refused: no further information

rocks.inspectit.shared.all.kryonet.TcpConnection.connect(TcpConnection.java:145)
	... 53 common frames omitted
Wrapped by: java.io.IOException: Unable to connect to: localhost/

Please let me know how to fix this? Thanks

**Comment by ivansenic** [comment]
Seems that your repository information in the agent start-up properties are wrong. The agent tries to connect to `localhost/`, please use `-Dinspectit.repository=localhost:9070` (if you are running locally).

**Comment by abk267** [comment]
Thank you. It worked. But I am not able to see all package invocations and methods invoked .
I can also see doFilter for the most part and some sql ... How do I get a sequence diagram where I get a clear picture of a use case? Please let me know.
Thanks

**Comment by ivansenic** [comment]
You need to configure where to insert measurement points.. You can do this in the configuration, please read https://inspectit-performance.atlassian.net/wiki/spaces/DOC18/pages/93009274/Configuration+basics for all information.

**Comment by abk267** [comment]
Thanks. Could you please send me an example ? 
ThanksAsha

**Comment by ivansenic** [comment]
You can check the examples by importing the following configuration that was developed for the Spring Petclinic app: https://github.com/inspectit-labs/spring-petclinic-microservices/blob/inspectit/inspectit/petclinic_instrumentation_config.xml
