### ISSUE TITLE
Hitting java.lang.NoClassDefFoundError: java/sql/SQLException during agent startup

### ISSUE THREAD

**Issue by narayankarthi** [inspectIT/inspectIT#387]
PS D:\> java -javaagent:D:\InspecIt\agent\inspectit-agent.jar "-DInspectit.repository=localhost=9070" "Dinspectit.agent.
name=D:\1557\spring-web-application" -jar .\spring-web-application-1.0.0-SNAPSHOT.jar
May 03, 2018 3:46:06 PM rocks.inspectit.agent.java.javaagent.JavaAgent premain
INFO: inspectIT Agent: Starting initialization...
15:46:07.217 [main] INFO rocks.inspectit.agent.java.SpringAgent - Location of inspectit-agent.jar set to: D:\InspecIt\agent\inspectit-agent.jar
2018-05-03 15:46:07,400: [inspectIT] 254    [           main] INFO  spectit.agent.java.SpringAgent - Initializing Spring on inspectIT Agent...
2018-05-03 15:46:07,583: [inspectIT] 437    [           main] ERROR spectit.agent.java.SpringAgent - inspectIT agent initialization failed. Agent will not be active.
May 03, 2018 3:46:07 PM rocks.inspectit.agent.java.javaagent.JavaAgent preloadClasses
INFO: Preloading classes ...
May 03, 2018 3:46:07 PM rocks.inspectit.agent.java.javaagent.JavaAgent preloadClasses
INFO: Preloading classes complete...
May 03, 2018 3:46:07 PM rocks.inspectit.agent.java.javaagent.JavaAgent premain
INFO: inspectIT Agent: Initialization complete...
Error: Could not find or load main class Dinspectit.agent.name=D:\1557\spring-web-application
Caused by: java.lang.ClassNotFoundException: Dinspectit.agent.name=D:\1557\spring-web-application

**Comment by narayankarthi** [comment]
java -javaagent:D:\InspecIt\agent\inspectit-agent.jar "-DInspectit.repository=localhost=9070" "Dinspectit.agent.
name=D:\1557\spring-web-application" -jar .\spring-web-application-1.0.0-SNAPSHOT.jar

what is agent name

**Comment by ivansenic** [comment]
Agent name is some name that you choose. It can be anything you want. Be careful you have the mistake in your repository property as well:

`-Dinspectit.repository=localhost:9070 -Dinspectit.agent.name=MyAppName`

**Comment by narayankarthi** [comment]
[inspectIT] 478    [           main] ERROR spectit.agent.java.SpringAgent - inspectIT agent initialization failed. Agent will not be active. 

im facing this problem after correcting agent name

**Comment by ivansenic** [comment]
What's log saying before that? Have you started the inspectIT CMR, otherwise agent cannot connect to pull the configuration?

**Comment by narayankarthi** [comment]
![powershell inspectit](https://user-images.githubusercontent.com/29753764/39576712-b79302dc-4efc-11e8-8001-b4fe11326903.png)

**Comment by narayankarthi** [comment]
first i started CMR as batch file startup batch file and finishing that i started inspectit

**Comment by ivansenic** [comment]
You have capital **I** in the -Dinspectit.repository property. Please change the:

`-DInspectit.repository=localhost:9070` to `-Dinspectit.repository=localhost:9070`

**Comment by narayankarthi** [comment]
![inspect it 1](https://user-images.githubusercontent.com/29753764/39577924-50df006e-4f00-11e8-8c00-128a8db2de92.png)
same error

**Comment by narayankarthi** [comment]
[agent.log](https://github.com/inspectIT/inspectIT/files/1971043/agent.log)

**Comment by ivansenic** [comment]
OK, I understand. You are hitting the: `java.lang.NoClassDefFoundError: java/sql/SQLException`

Can you tell me what version of Java are you using and what version of inspectIT?

**Comment by narayankarthi** [comment]
java 1.8

**Comment by ivansenic** [comment]
Are you sure? This looks like an error that would come with java 9 as `java.sql.Exception` is now part of the `java.sql` module and might not be available. Can you execute `java -version` in the same power-shell you are trying to run the application?

We did have a commit for the support of Java 9, but I think this is part of 1.8.5 version, can you try to update to latest inspectIT version?

**Comment by narayankarthi** [comment]
java 9 in powershell 
what is latest inspectIT version ?Please share it i will try it and update it

**Comment by ivansenic** [comment]
https://github.com/inspectIT/inspectIT/releases/tag/1.8.5.101

**Comment by narayankarthi** [comment]
Thank you for your information inspect it agent is added but how can i monitor application ?

**Comment by narayankarthi** [comment]
![image](https://user-images.githubusercontent.com/29753764/39624287-60e4d914-4fb6-11e8-88a1-cd26b4fc04eb.png)

which jre want to used

**Comment by narayankarthi** [comment]
its working by using JDK 1.8 of JRE Environment
by refer link https://www.youtube.com/watch?v=T5NASfOGCGQ

**Comment by narayankarthi** [comment]
how without internet works

**Comment by ivansenic** [comment]
New release (1.9.2) is available. Closing as no more concrete questions to answer.
