### ISSUE TITLE
I cannot navigate metrics collected in the past

### ISSUE THREAD

**Issue by frepola** [inspectIT/inspectIT#394]
I configured successfully InfluxDB and I'm able to see standard Dashboard graphs with Grafana. I believe that it should be possible to see metrics collected in the past and stored into InfluxDB into InspectIT client as a calls drill down. Unfortunately when I try to change Time Range (i.e. into Http Timer Data --> URI Aggregation) no metrics are visible even if into Grafana I'm continuing to see them.
Moreover I noticed that if metrics are stored thhrough a storage recording they are visible but this mean to store them into InfluxDB and into physical disk too.

Is there an option to solve this issue or this is a normal behavior?

**Comment by ivansenic** [comment]
You are hitting the normal behavior I would say. Currently, once metrics are stored in the influxDB we cannot show them in the UI. It's a pity yes, but unfortunately, the limitation that could not be avoided at the moment. The recording is something else, ones you activate it everything is stored to the storage in addition.

**Comment by frepola** [comment]
thanks for your support
