### ISSUE TITLE
View an exception in inspectIT console

### ISSUE THREAD

**Issue by rocklala** [inspectIT/inspectIT#399]
I download and install inspectIT for windows stable version and then configure tomcate and jboss agent and its connected successfully...I deployed my war file into tomcat and jboss. So now I want to view exception. Is there any way to generate the manual exception, so that i can view the exception in InspectIt console

**Comment by ivansenic** [comment]
Instrument one or more exceptions from the `java.` package. You would be able to see them quite quickly.
