### ISSUE TITLE
InspectIT UI is frozen on OSX 10.14 - with JDK8 (Open/Oracle/Zulu)

### ISSUE THREAD

**Issue by svenruppert** [inspectIT/inspectIT#404]
It just starts the UI, is looking for updates..  frozen..

**Comment by svenruppert** [comment]
inspectit.installer-all.macosx.x64-1.9.2.106.jar

**Comment by ivansenic** [comment]
Do you start it with `run.sh` that's provided in the root dir?

**Comment by svenruppert** [comment]
any news here ?

**Comment by ivansenic** [comment]
No time to check this one yet.. Will post updates here as soon as possible..

**Comment by svenruppert** [comment]
ok, don´t need it anymore
