### ISSUE TITLE
Prevent startup order issues using connection retry

### ISSUE THREAD

**Issue by lentus** [inspectIT/inspectIT#410]
### Problem
I am using a docker-compose setup that includes a CMR server and several backend servers with InspectIT Agents. When I do a 'docker-compose up', it often happens that multiple agents fail to connect to the CMR, because it is not yet ready to accept agent connections.

### What I have tried
The depends_on section in Docker makes sure that certain containers are started before others, but does not wait for those containers to pass any healthcheck. The [Docker documentation](https://docs.docker.com/compose/startup-order/) recommends the use of scripts like [wait-for-it](https://github.com/vishnubob/wait-for-it), but those require some sort of health check to be present in the application you want to wait for. I have not found such a health check for the CMR in the InspectIT documentation.

### Possible solutions
If there is something I can use as a healthcheck for the CMR and I just missed it, please let me know. If not, it would be great if such a feature could be implemented. 

Another approach would be to have the Agent retry connecting to the CMR a number of times before giving up.

**Comment by ivansenic** [comment]
Hi,

You can use the `http://localhost:8182/rest/cmr/version` as the health check. This will output the version of the CMR once it has been started.

We are using the same in our CMR docker image: https://github.com/inspectit-docker/cmr/blob/master/Dockerfile

Let me know if I can close this?

Cheers,
Ivan

**Comment by lentus** [comment]
Hi Ivan, 

I just noticed that as well. Yes, this can be closed. Thanks for your quick response!

Cheers,
Wouter
