### ISSUE TITLE
Links to license broken in README.md

### ISSUE THREAD

**Issue by duelle** [inspectIT/inspectIT#81]
The README.md file contains links to the license that are broken:
- License plate
- Licensing section

They link to:
`https://github.com/inspectIT/inspectIT/blob/master/LICENSE.txt`
but should link to:
`https://github.com/inspectIT/inspectIT/blob/master/license/LICENSE.txt`

**Comment by mariusoe** [comment]
I've copied this issue to the inspectIT Jira.
Link to the ticket: https://inspectit-performance.atlassian.net/browse/INSPECTIT-2092

**Comment by ivansenic** [comment]
Fixed with #82.
