### ISSUE TITLE
How is the overhead of InspectIT?

### ISSUE THREAD

**Issue by xiaomutoun123** [inspectIT/inspectIT#93]
Hi,

I am in a project of evaluating different APM tools and I find that InspectIT is quite good to use. But I didn't find any information about the overhead of this tool. So can anyone tell me about the overhead of InspectIT on the monitored web server? Is there any documents explaining about it? Looking forward for your help.

**Comment by ivansenic** [comment]
Hi,

We often get questions about overhead and the answer is not easy. 

Basically depends on how do you use the tool, that's the first thing that should be clarified. First of all depends how many methods are you instrumenting, more methods of course mean more overhead. Second it depends on execution frequency of instrumented methods. You will agree that instrumenting a method that is executed once per user transaction will bring much less overhead than instrumenting the method like hashCode() that is executed millions of times. Furthermore, thinking in percentages (like overhead is 3%) is usually not possible, as this is directly influenced by the duration of the instrumented methods. If you instrument method that is executed in few nanoseconds, than overhead is suerly over 1000%, while if you instrument method which execution takes 1s then overhead in percentages is most likely to be around 0.1%. Thus, the used configuration very much influences the total overhead brought to the monitored application.

The second part of the story is usually _"OK, I get that but tell me how much time is spent in inspectIT sensors when I place one of them on my method"_. Here I could guide you to several sources:

- Jan Waller form the Computer Science Department of Kiel University wrote the book [Performance Benchmarking of Application Monitoring Frameworks](http://www.amazon.com/Performance-Benchmarking-Application-Monitoring-Frameworks/dp/3735778534) where he tested inspectIT and provided the full chapter on it's performance/overhead. This chapter is also available on our [Documentation page](https://inspectit-performance.atlassian.net/wiki/download/attachments/5019245/inspectIT-benchmarks.pdf?api=v2).
- Some additional, but quite outdated information you can find on the Exception Sensor overhead documentation on our [Wiki](https://inspectit-performance.atlassian.net/wiki/display/DOC16/Exception+Sensor)

At the moment we are developing the JMH tests for our sensors. As soon these are done, we will publish the detailed information about the performance of each sensor in various scenarios.

In addition in next few months we will be supervising the bachelor thesis _Performance analysis of an application monitoring tool_, with the inspectIT as the monitoring tool. The analysis should identify the performance limits and why they are reached.

If you have any further questions, please let us know.

**Comment by xiaomutoun123** [comment]
Hi, 

Thanks a lot for your response. It's really helpful. 

You said that the overhead depends on the extent of instrumentation. So is inspectIT able to control the amount of methods to instrument? Is it able to configure the overhead it brings to the system?
Thanks in advance for your response.

**Comment by stefansiegl** [comment]
Hi,

The easiest way to check which instrumentations have the highest impact onto overhead is for you to regularly check the extend of the instrumentation per method. As @ivansenic pointed out a quite good estimate is the number of times an instrumentation was invoked. You have an easy way of doing this. Simply navigate to the timer view. Here you see all method invocations for the selected time period. Simply sort by execution count. You now see the instrumentations that were executed the most. 

Go over the list starting from the most frequently called and ask yourself: Do i need this data or can I go without it? If you can go without it remove it from instrumentation.

That said we are currently researching ways of dynamically adapting the instrumentation and also other ways of capturing the data using sampling approaches. 

hope this helps,
Stefan

**Comment by ivansenic** [comment]
Hi,

Yes inspectIT can 100% control the instrumentation configuration. Please check the [Agent Configuration](https://inspectit-performance.atlassian.net/wiki/display/DOC16/Agent+Configuration) documentation in order to get more info on this topic.

**Comment by stefansiegl** [comment]
@xiaomutoun123 Did this answer your question? I would like to close this issue if this is the case. Is this ok for you?

**Comment by xiaomutoun** [comment]
Yes, the answer is perfect. You can close this issue. Thanks.
